title: Vaitea Opuu
email: "vaiteaopuu@gmail.com"
description: PostDoc at Max Planck Institute for Mathematics in the Sciences, Leipzig, Germany

repository: "vaiteaopuu/website"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# A list of the pages to display in the navigation bar
header_pages:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude: