# What I do now
Hi! I'm a Postdoc in the group Structure of evolution, at the Max Planck
Institute for Mathematics in Sciences (Leipzig, Germany). I currently work on
computational method to design RNA molecules. Those methods rely on statistical
physics, neural-network, or dynamic programming.

# Short academic path
After a Master in Bioinformatics at Paris-Saclay university (2015-2017), I
started a PhD in biology at Ecole Polytechnique (Institut Polytechnique de
Paris). From 2017 to 2020, I worked on computational protein design under the
supervision of Thomas Simonson in the Structural Biology of the Cell. I defended
my PhD the 29th of October 2020.

* Research interests
# Bio-polymer design
My main interest are:
- Design of bio-polymers (RNA, DNA, Proteins) using their bio-physical-chemical
  properties.
- Design methods/algorithm to study those bio-polymers

* Publications
** (Journal) Adaptive Landscape Flattening Allows the Design of Both Enzyme: Substrate Binding and Catalytic Power
- Plos Computational Biology, 2020
Vaitea Opuu, Giuliano Nigro, Thomas Gaillard, Emmanuelle Schmitt, Yves Mechulam, Thomas Simonson
** (Journal) A Physics-Based Energy Function Allows the Computational Redesign of a Pdz Domain
- Scientific Reports, 2020
Vaitea Opuu*, Young Joo Sun*, Titus Hou, Nicolas Panel, Ernesto J. Fuentes, Thomas Simonson
** (Journal) Computational Design of Fully Overlapping Coding Schemes for Protein Pairs and Triplets
- Scientific Reports, 2017
Vaitea Opuu, Martin Silvert, Thomas Simonson
** Proteus software for physics-based protein design
- The Journal of Physical Chemistry Part A, 2020
Mignon David, Druart Karen*, Michael Eleni*, Vaitea  Opuu*, Polydorides Savvas*, Villa Francesco*, Gaillard Thomas, Panel Nicolas, Archontis Georgios, Simonson Thomas
** (Journal) Meet-U: educating through research immersion
- Plos Computational Biology, 2018
Abdollahi Nika, ...
** (Book Chapter) in Methods in Molecular Biology: PDZ domains 
- methods in Molecular Biology: PDZ domains
Panel Nicolas, Vaitea  Opuu, Villa Francesco, Mignon David, Simonson Thomas
* CV
# point to the latex document
[[cv/cv.pdf]]

* Others
